# Generated by Django 5.2 on 2025-07-08 02:14

import django.db.models.deletion
import django.utils.timezone
import signalguideapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='設備名稱')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最後更新')),
            ],
            options={
                'verbose_name': '設備',
                'verbose_name_plural': '設備列表',
            },
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='作業類別名稱')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最後更新')),
            ],
            options={
                'verbose_name': '作業類別',
                'verbose_name_plural': '作業類別列表',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('employee_id', models.CharField(max_length=5, unique=True, validators=[signalguideapp.models.validate_five_digit_id], verbose_name='員工編號')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('role', models.CharField(choices=[('A', '管理者'), ('B', '查詢者')], default='B', max_length=1)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '員工帳號',
                'verbose_name_plural': '帳號管理',
                'ordering': ['employee_id'],
            },
            managers=[
                ('objects', signalguideapp.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='FaultCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='故障徵狀')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最後更新')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faults', to='signalguideapp.device')),
            ],
            options={
                'verbose_name': '設備故障案例',
                'verbose_name_plural': '設備故障案例列表',
            },
        ),
        migrations.CreateModel(
            name='ProcedureStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.PositiveIntegerField(verbose_name='步驟順序')),
                ('instruction', models.TextField(verbose_name='處理說明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最後更新')),
                ('fault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='signalguideapp.faultcase')),
            ],
            options={
                'verbose_name': '故障處理步驟',
                'verbose_name_plural': '故障處理步驟列表',
                'ordering': ['step_order'],
            },
        ),
        migrations.CreateModel(
            name='SignalGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(max_length=100, verbose_name='系統')),
                ('subsystem', models.CharField(blank=True, max_length=100, verbose_name='子系統')),
                ('equipment_type', models.CharField(blank=True, max_length=100, verbose_name='設備類別')),
                ('doc_number', models.CharField(max_length=50, unique=True, verbose_name='文件編號')),
                ('title', models.CharField(max_length=200, verbose_name='文件名稱')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='權責股')),
                ('owner', models.CharField(blank=True, max_length=100, verbose_name='負責人員')),
                ('file', models.FileField(blank=True, upload_to='manuals/', verbose_name='上傳檔案')),
                ('is_frequently_used', models.BooleanField(default=False, verbose_name='是否為熱門文件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最後更新')),
                ('job_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guides', to='signalguideapp.jobtype', verbose_name='作業類別')),
            ],
            options={
                'verbose_name': '工作說明書',
                'verbose_name_plural': '工作說明書列表',
                'ordering': ['job_type', 'system', 'title'],
            },
        ),
        migrations.AddField(
            model_name='device',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='signalguideapp.signalguide'),
        ),
    ]
