# Generated by Django 5.2 on 2025-07-04 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignalGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('device_name', models.CharField(max_length=200)),
                ('error_description', models.TextField()),
                ('file', models.FileField(upload_to='manuals/')),
            ],
        ),
    ]
