# Generated by Django 5.2 on 2025-07-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signalguideapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signalguide',
            name='is_frequently_used',
        ),
        migrations.AddField(
            model_name='signalguide',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='是否置頂'),
        ),
    ]
