# Generated by Django 5.2 on 2025-07-08 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signalguideapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': '設備', 'verbose_name_plural': '設備列表'},
        ),
        migrations.AlterModelOptions(
            name='faultcase',
            options={'verbose_name': '設備故障案例', 'verbose_name_plural': '設備故障案例列表'},
        ),
        migrations.AlterModelOptions(
            name='procedurestep',
            options={'ordering': ['step_order'], 'verbose_name': '故障處理步驟', 'verbose_name_plural': '故障處理步驟列表'},
        ),
    ]
