# Generated by Django 5.2 on 2025-07-07 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signalguideapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['employee_id'], 'verbose_name': '員工帳號', 'verbose_name_plural': '帳號管理'},
        ),
        migrations.AlterModelOptions(
            name='signalguide',
            options={'ordering': ['category', 'title'], 'verbose_name': '工作說明書', 'verbose_name_plural': '工作說明書列表'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('A', '管理者'), ('B', '查詢者')], default='B', max_length=1),
        ),
    ]
