# Generated by Django 5.2 on 2025-07-07 00:55

import signalguideapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signalguideapp', '0002_alter_customuser_options_alter_signalguide_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='employee_id',
            field=models.CharField(max_length=5, unique=True, validators=[signalguideapp.models.validate_five_digit_id], verbose_name='員工編號'),
        ),
    ]
